### ISSUE TITLE
Integración Heroku

### ISSUE THREAD

**Issue by Diiru** [IIC2143-2017/syllabus#10]
Hola !
Estaba intentando conectar mi app con el deploy automático de Heroku. Ya lo he hecho antes con otras apps pero esta vez no me funciono. Creo que puede ser por los permisos de la organización (note que los habilitaron para poder usar Heroku, pero aun así no funciona) o directamente porque el repo no es mio.

Esto me sale cuando intento agregar el repositorio:
<img width="1388" alt="screen shot 2017-09-06 at 20 38 25" src="https://user-images.githubusercontent.com/13814193/30139301-67bff028-9343-11e7-8ef3-cc076c3424f4.png">

Que podría hacer ? Tener un repo privado e ir sincronizandolo cada vez ? Usar otro Addon ? Alguna forma manual para agregar la integración ?

Gracias de antemano !!

**Comment by JaimePata** [comment]
Es raro que no pudieras a la primera, pero debería solucionarse pidiendo permiso para tu repositorio.
Cuando apretas el botón que dice conectar con github (antes de la pantalla que muestras en tu screenshot) te debería haber salido un menú similar a este, que acabo de probar con mi cuenta:
<img width="1388" alt="screen shot 2017-09-06 at 20 38 25" src="https://image.prntscr.com/image/dmIKoyQVQS_sV6ZU8UZUpQ.png">
Los repositorios en que puedo apretar el botón de request son repositorios manejados por una organización que no administro. Si mandas la request algún ayudante debería poder aceptarla.

**Comment by Diiru** [comment]
Si trate de hacer eso, pero me dice que ya esta listo el acceso, por eso no entiendo que no me deje.

**Comment by JaimePata** [comment]
Que extraño :/

En todo caso, la solución que propones es válida y te contaría el bonus. Sin embargo, acuerdate de que el repo del curso tiene que estar al día con lo que entreguen en cada sprint.
