### ISSUE TITLE
Error desconocido

### ISSUE THREAD

**Issue by narierao** [IIC2143-2017/syllabus#12]
Tengo este error al iniciar nuevamente mi App, no hice ningún cambio desde que la usé por última vez.
El orden de los comandos que uso son:

bundle install 
rake db:migrate
rails -s

Halp :c

![captura de pantalla de 2017-10-22 14-48-48](https://user-images.githubusercontent.com/20784195/31864694-492e1bc6-b738-11e7-8c4b-680f2b4e3ac2.png)

**Comment by mf222** [comment]
A primera vista parece ser que tiene que ver con algún seed que no cumple las condiciones, o algun valor antiguo que no hasido actualizado en la bd. ¿Qué tiene un lista_reproduccions_controller_test? Si tienes poblada la bd con datos desactualizados prueba con `rails db:reset`.
