### ISSUE TITLE
Ayudantía - Duda sobre pregunta 2

### ISSUE THREAD

**Issue by AlfonsoIgnacioV** [IIC2143-2017/syllabus#3]
Hola, mi duda consiste en qué parte del controlador se debería modificar. Yo estaba pensando en hacer que cuando el controlador de gadgets intente hacer **new**, recibiendo el parámetro del gadget, pueda hacer esta verificación. ¿Sería una solución válida? ¿Cómo se haría para, dado un ID, ir a la base de datos a buscar cuántas unidades de cada gadget hay?
Espero se entienda
Muchas gracias
Saludos

**Comment by ifcarrera** [comment]
Hola!
Solo te pide hacer ese método. Supón que es algo como `verificar_stock(id_gadget)` y trabaja en ese método. Para acceder a instancias en particular, recuerda que existe el método `find_by(atributo: parametro)`, donde atributo puede ser cualquier columna de tu DB, y el parámetro es según lo que quieras filtrar.
