### ISSUE TITLE
schema.rb

### ISSUE THREAD

**Issue by javierlopeza** [IIC2143-2017/syllabus#4]
¿Para la prueba es necesario saber cómo es el archivo `schema.rb`? Que nunca lo editamos directamente (solo con migrations).

**Comment by mf222** [comment]
Sí, es necesario. El primer ejercicio de la ayudantia del día viernes se trato de como era el schema y como se modificaba este. Si bien no se creo desde cero en ninguna ayudantia, se explicó que *desde la migración se creaba ese archivo* y como estaba compuesto el archivo. El punto de saber como son los archivos no es que no se usen ni migraciones ni generadores, si no *saber que es exáctamente lo que crean*.

**Comment by javierlopeza** [comment]
Perfecto, gracias!
