### ISSUE TITLE
Ayudantía recuperativa

### ISSUE THREAD

**Issue by Treisenegger** [IIC2143-2017/syllabus#5]
En la ayudantía del viernes se comentó que quizás se iba a subir la solución de la ayudantía recuperativa al sitio. ¿Esto será posible, para poder verificar que estemos haciendo lo que se espera?

**Comment by mf222** [comment]
Lo evaluaremos. De todas formas el procedimiento de la prueba es el siguiente:

* Si se realiza algo con migraciones o generadores, se debe explicar exactamente el archivo que se crea o modifica y lo que contiene.
* Hay que enumerar los pasos.

Planeamos darles un recordatorio del árbol de carpetas y archivos por defecto de Rails.
