### ISSUE TITLE
Instalación psql

### ISSUE THREAD

**Issue by fernddevidts** [IIC2143-2017/syllabus#6]
Hola,

Estaba tratando de instalar psql en OS X 10.12.6 (Sierra) y usé el instalador de EnterpriseDB. Cuando se terminó la instalación reinicié el computador y en el revisé la versión de psql pero me dice "no such file or directory". Busqué en internet y parece que pueden haber problemas con las shared libraries pero no sé como solucionarlo.

También traté de instalarlo con Homebrew pero al tratar de crear un usuario me pide una contraseña (que no es la de mi computador) y no sé qué hacer con eso.

Gracias!

**Comment by ifcarrera** [comment]
Hola! 
Te recomiendo instalar Postgres.app, encuentro que es más amigable y fácil de instalar.
Saludos!

**Comment by fernddevidts** [comment]
Gracias!
