### ISSUE TITLE
Problemas instalación Rails Mac

### ISSUE THREAD

**Issue by fcgfaura** [IIC2143-2017/syllabus#7]
Hola!, ya instalé Ruby, pero creo que no lo hace global, porque cuando ejecuto `rbenv global 2.4.0` y luego `ruby -v` me aparece `ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]`.
Entonces cuando ejecuto `gem install rails -v 5.0.2` me tira un error de permisos así que lo ejecuté con `sudo`, y me tiró:

```
Fetching: i18n-0.8.6.gem (100%)
Successfully installed i18n-0.8.6
Fetching: thread_safe-0.3.6.gem (100%)
Successfully installed thread_safe-0.3.6
Fetching: tzinfo-1.2.3.gem (100%)
Successfully installed tzinfo-1.2.3
Fetching: minitest-5.10.3.gem (100%)
Successfully installed minitest-5.10.3
Fetching: concurrent-ruby-1.0.5.gem (100%)
Successfully installed concurrent-ruby-1.0.5
Fetching: activesupport-5.0.2.gem (100%)
ERROR:  Error installing rails:
	activesupport requires Ruby version >= 2.2.2.
```

Qué puedo hacer?

**Comment by santiagocruzb** [comment]
Tengo el mismo error en 2 computadores. Poniendo `rbenv version` me sale que efectivamente tengo `2.4.0 (set by /Users/santiagocruz/.rbenv/version)`
Intenté

- `gem install rails -v 5.0.2 --user-install`

- `sudo gem install rails -v 5.0.2 -n/usr/local/bin`

- `gem install rails -v 5.0.2 --user-install -n~/bin`

- `sudo gem install -n /usr/local/bin rails -v 5.0.2`

Saludos

**Comment by mf222** [comment]
Estimados, ¿qué versión de mac tienen? ¿es Sierra o El Capitan? Si es así es probablemente que deban añadir el path al archivo de profile de la terminal que usan, Sierra por ejemplo viene con zsh por defecto, por lo que en vez de modificar el archivo bashrc o bash_profile deberan editar el zshrc o zsh_profile.  

Revisen si tienen estas lineas en esos archivos de su terminal por defecto (bash o zsh):

```
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"
```

Si tuvieron que añadir estas lineas, reinicien la terminal para que pueda correr las nuevas instrucciones.

**Comment by santiagocruzb** [comment]
Tengo Yosemite.
Eso funciona. Muchas gracias!
