### ISSUE TITLE
Busco Integrante de Grupo

### ISSUE THREAD

**Issue by devpablin** [IIC2143-2017/syllabus#9]
Hola soy Pablo Gonzales y con Nicolas Deltheil buscamos un integrante para completar nuestro grupo

**Comment by Mnfriedl** [comment]
Hola, aún les falta?

**Comment by devpablin** [comment]
Escribeme a mi correo pegonzales@uc.cl

**Comment by dtfuller** [comment]
Hola a todos! Con Pablo Pino también nos falta un integrante, si alguien quiere ser con nosotros feliz ;) Escriban a pdpino@uc.cl o dtfuller@uc.cl
